### ISSUE TITLE
CI Setup

### ISSUE THREAD

**Issue by dchiu911** [AlineTalhouk/splendid#44]
Hi @AlineTalhouk,

A couple simple continuous integration setup tasks for automated package checking:

- [x] Travis: flick the switch for **AlineTalhouk/splendid** at https://travis-ci.org/profile/AlineTalhouk (sync account if you don't see it)
- [x] AppVeyor: turn on AppVeyor for this repo at https://ci.appveyor.com/projects/new

Afterwards I will add the appropriate infrastructure.

**Comment by AlineTalhouk** [comment]
@dchiu911 please check that it works and close issue when done.
